name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile_and_run_tests:
    runs-on: ubuntu-latest
    env:
      working-directory: '.'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install hardhat
        run: npm install --save-dev hardhat
        working-directory: ${{env.working-directory}}
      - name: Install packages
        run: npm ci
        working-directory: ${{env.working-directory}}
      - name: Compile code
        run: npm run compile
        working-directory: ${{env.working-directory}}
      - name: Run tests
        run: npm run test
        working-directory: ${{env.working-directory}}
